name: MT
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - cython=0.26.1=py36hd51f8eb_0
  - dbus=1.13.16=h18a8e69_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.9=hb1e8313_2
  - freetype=2.10.2=ha233b18_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.65.0=hc5f4afa_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=1.7.0=py36_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2019.4=233
  - ipykernel=5.3.3=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.1=py36_0
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py36_0
  - kiwisolver=1.2.0=py36h04f5b5a_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - llvm-openmp=10.0.0=h28b9765_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py36h5670ca0_0
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.1.0=py36hc64f4ea_0
  - mkl_random=1.1.1=py36h959d312_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=h0a44026_1
  - networkx=2.4=py_1
  - notebook=6.0.3=py36_0
  - numpy=1.18.5=py36h55a193a_0
  - numpy-base=1.18.5=py36h3304bdc_0
  - openssl=1.1.1g=h1de35cc_0
  - packaging=20.4=py_0
  - pandas=1.0.5=py36h959d312_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.7.0=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=20.1.1=py36_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - psutil=5.7.0=py36h1de35cc_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h655552a_2
  - pyrsistent=0.16.0=py36h1de35cc_0
  - python=3.6.10=hf48f09d_2
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pyzmq=19.0.1=py36hb1e8313_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - scikit-learn=0.23.1=py36h603561c_0
  - scipy=1.5.0=py36h912ce22_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py36_0
  - setuptools=49.2.0=py36_0
  - sip=4.19.8=py36h0a44026_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=hffcf06c_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.0.4=py36h1de35cc_1
  - traitlets=4.3.3=py36_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.2=hb1e8313_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/anton/miniconda3/envs/MT

